services:
  - type: web
    name: tripify-backend
    env: node
    rootDir: tripify-backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
      - key: PORT
        value: 5000
      - key: FRONTEND_ORIGIN
        value: https://tripify-frontend.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false

  - type: static
    name: tripify-frontend
    rootDir: tripify-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        value: https://tripify-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
